"""PersonaFactory — generate Thai-grounded synthetic consumer personas using LLM.

Each persona is a detailed synthetic consumer with:
- Demographics sampled from regional distributions
- Psychographics derived from Thai cultural values
- A narrative backstory generated by LLM
- OASIS-compatible profile for simulation
"""
import random
import logging
from typing import Dict, Any, List, Optional
from datetime import datetime, timezone

from ..models.persona import (
    ThaiPersona, PersonaAttribute, ThaiRegion, IncomeLevel,
    EducationLevel, ThaiValueDimension, PurchaseDecisionStyle,
    MediaChannel,
)
from ..models.campaign import CampaignTarget
from .thai_context import (
    REGION_POPULATION, REGION_PROFILES, CONSUMER_ARCHETYPES,
    THAI_NAMES,
)
from ..llm.provider_factory import LLMProviderFactory
from ..config import Config

logger = logging.getLogger('mirofish.persona_factory')


class PersonaFactory:
    """Generate grounded Thai consumer personas for simulation campaigns."""

    MAX_RETRIES = 2

    def __init__(self, llm_client=None):
        self.llm = llm_client or LLMProviderFactory.get_provider('simulation')

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_batch(
        self,
        org_id: str,
        campaign_id: str,
        target: CampaignTarget,
        count: int = 100,
        language: str = "th",
    ) -> List[ThaiPersona]:
        """Generate a batch of personas matching campaign target.

        Strategy:
        1. Distribute count across archetypes matching target demographics
        2. For each archetype, generate base attributes (demographic sampling)
        3. Use LLM to generate narrative backstory (batch 5 at a time)
        4. Assemble complete ThaiPersona objects
        """
        personas: List[ThaiPersona] = []

        # Step 1: Select matching archetypes
        archetypes = self._select_archetypes(target, count)
        archetype_counts = self._distribute_count(count, archetypes)

        # Step 2 & 3: Generate per archetype group
        persona_id = 0
        for arch_name, arch_count in archetype_counts.items():
            arch = CONSUMER_ARCHETYPES[arch_name]

            for _ in range(arch_count):
                persona_id += 1
                attrs = self._generate_attributes(arch, target)
                persona = ThaiPersona(
                    org_id=org_id,
                    campaign_id=campaign_id,
                    persona_id=f"per_{org_id}_{campaign_id}_{persona_id:04d}",
                    **attrs.model_dump(),
                )
                personas.append(persona)

        # Step 3: Generate narratives in batches
        self._generate_narratives_batch(personas, language)

        # Step 4: Assign social relationships
        self._assign_social_graph(personas)

        logger.info(
            f"Generated {len(personas)} personas for campaign {campaign_id} "
            f"(org={org_id}, target={target.segment_name})"
        )
        return personas

    # ------------------------------------------------------------------
    # Archetype selection & distribution
    # ------------------------------------------------------------------

    def _select_archetypes(self, target: CampaignTarget, count: int) -> List[str]:
        """Select consumer archetypes that match the campaign target."""
        available = list(CONSUMER_ARCHETYPES.keys())

        # Filter by age range
        matching = []
        for name, arch in CONSUMER_ARCHETYPES.items():
            arch_min, arch_max = arch["age_range"]
            target_min, target_max = target.age_range
            # Overlap check
            if arch_max >= target_min and arch_min <= target_max:
                matching.append(name)

        # Filter by regions (if specified)
        if target.regions and "Bangkok" not in "".join(target.regions):
            # Remove Bangkok-heavy archetypes if Bangkok not in target
            matching = [m for m in matching if "bangkok" not in CONSUMER_ARCHETYPES[m]["regions"] or
                       any(r.lower() in [t.lower() for t in target.regions] for r in CONSUMER_ARCHETYPES[m]["regions"])]

        # Ensure at least 2 archetypes
        if len(matching) < 2:
            matching = available[:3]

        return matching

    def _distribute_count(self, count: int, archetypes: List[str]) -> Dict[str, int]:
        """Distribute persona count across archetypes with regional weighting."""
        distribution = {}
        weights = []

        for arch in archetypes:
            arch_data = CONSUMER_ARCHETYPES[arch]
            # Weight by population of matching regions
            region_weight = sum(
                REGION_POPULATION.get(r, 1.0)
                for r in arch_data["regions"]
            )
            weights.append(region_weight)

        total_weight = sum(weights)
        remaining = count

        for i, arch in enumerate(archetypes):
            if i == len(archetypes) - 1:
                distribution[arch] = remaining
            else:
                share = max(1, int(count * weights[i] / total_weight))
                distribution[arch] = share
                remaining -= share

        return distribution

    # ------------------------------------------------------------------
    # Attribute generation
    # ------------------------------------------------------------------

    def _generate_attributes(
        self, archetype: Dict[str, Any], target: CampaignTarget
    ) -> PersonaAttribute:
        """Generate grounded PersonaAttribute from archetype template."""
        arch = archetype

        # Select region weighted by population
        regions = arch["regions"]
        region_weights = [REGION_POPULATION.get(r, 1.0) for r in regions]
        region = random.choices(regions, weights=region_weights, k=1)[0]

        # Age within archetype range, clipped to target
        age_min, age_max = arch["age_range"]
        target_min, target_max = target.age_range
        age = random.randint(max(age_min, target_min), min(age_max, target_max))

        # Gender
        gender = target.gender if target.gender != "all" else random.choice(["male", "female"])

        # Income
        income = IncomeLevel(arch["income"])

        # Education
        education = EducationLevel(random.choice(["high_school", "vocational", "bachelors", "bachelors", "masters"]))

        # Values (2-4 from archetype emphasis + random)
        value_emphasis = [ThaiValueDimension(v) for v in arch["values"]]
        all_values = list(ThaiValueDimension)
        extra_values = random.sample([v for v in all_values if v not in value_emphasis],
                                     k=min(2, len(all_values) - len(value_emphasis)))
        values = value_emphasis + extra_values[:2]

        # Purchase decision
        decision = PurchaseDecisionStyle(random.choice([
            arch["decision"], arch["decision"],
            "brand_loyal", "impulsive", "social_proof",
        ]))

        # Behavior scores
        brand_loyalty = round(random.uniform(0.2, 0.8), 2)
        price_sensitivity = round(random.uniform(0.3, 0.9), 2)
        social_influence = round(random.uniform(0.3, 0.9), 2)
        innovation_openness = round(random.uniform(0.1, 0.7), 2)

        # Channels
        primary_channels = [MediaChannel(c) for c in random.sample(
            arch["channels"], k=min(3, len(arch["channels"]))
        )]

        # Spending
        spend_min, spend_max = arch["spending"]
        monthly_spending = random.randint(spend_min, spend_max)

        # Region profile
        region_profile = REGION_PROFILES.get(region, REGION_PROFILES["bangkok"])
        occupation = random.choice(region_profile["occupations"])
        if random.random() < 0.3:
            occupation = random.choice(arch.get("occupations", [occupation]))

        # Name
        name_pool = THAI_NAMES["male"] if gender == "male" else THAI_NAMES["female"]
        nick_pool = THAI_NAMES["nickname_male"] if gender == "male" else THAI_NAMES["nickname_female"]
        surname = random.choice(THAI_NAMES["surnames"])

        return PersonaAttribute(
            age=age,
            gender=gender,
            region=ThaiRegion(region),
            province=self._pick_province(region),
            income=income,
            education=education,
            occupation=occupation,
            values=values,
            decision_style=decision,
            brand_loyalty_score=brand_loyalty,
            price_sensitivity_score=price_sensitivity,
            social_influence_score=social_influence,
            innovation_openness=innovation_openness,
            primary_channels=primary_channels,
            influencer_susceptibility=round(random.uniform(0.2, 0.8), 2),
            monthly_spending_budget=monthly_spending,
            name=f"{random.choice(name_pool)} {surname}",
            nickname=random.choice(nick_pool),
        )

    def _pick_province(self, region: str) -> str:
        provinces = {
            "bangkok": ["กรุงเทพมหานคร"],
            "central": ["นนทบุรี", "ปทุมธานี", "อยุธยา", "นครปฐม", "สมุทรปราการ"],
            "north": ["เชียงใหม่", "เชียงราย", "ลำปาง", "พะเยา", "แม่ฮ่องสอน"],
            "northeast": ["นครราชสีมา", "ขอนแก่น", "อุดรธานี", "อุบลราชธานี", "บุรีรัมย์"],
            "east": ["ชลบุรี", "ระยอง", "จันทบุรี", "ฉะเชิงเทรา"],
            "south": ["ภูเก็ต", "สงขลา", "สุราษฎร์ธานี", "นครศรีธรรมราช", "กระบี่"],
            "west": ["กาญจนบุรี", "ราชบุรี", "เพชรบุรี", "ประจวบคีรีขันธ์"],
        }
        return random.choice(provinces.get(region, ["กรุงเทพมหานคร"]))

    # ------------------------------------------------------------------
    # LLM narrative generation (batched)
    # ------------------------------------------------------------------

    def _generate_narratives_batch(self, personas: List[ThaiPersona], language: str = "th"):
        """Generate narrative backstories for personas using LLM, in batches of 5."""
        batch_size = 5

        for i in range(0, len(personas), batch_size):
            batch = personas[i:i + batch_size]
            prompts = []

            for p in batch:
                prompt = self._build_narrative_prompt(p, language)
                prompts.append(prompt)

            # Try to generate narratives
            try:
                narratives = self._call_llm_for_narratives(prompts, language)
                for p, narrative in zip(batch, narratives):
                    p.persona_narrative = narrative
                    p.bio = narrative[:160] if narrative else ""
                    p.generation_model = self.llm.model
            except Exception as e:
                logger.warning(f"Narrative generation failed for batch {i}: {e}")
                # Fallback: use archetype narrative from context
                for p in batch:
                    for arch_name, arch in CONSUMER_ARCHETYPES.items():
                        if self._matches_archetype(p, arch):
                            p.persona_narrative = arch["narrative"]
                            p.bio = arch["narrative"][:160]
                            break

    def _build_narrative_prompt(self, persona: ThaiPersona, language: str) -> str:
        """Build LLM prompt for persona narrative generation."""
        region_info = REGION_PROFILES.get(persona.region.value, REGION_PROFILES["bangkok"])

        return f"""สร้างเรื่องราวชีวิต (backstory) ของผู้บริโภคชาวไทยคนนี้ ให้สมจริงและมีมิติ:

ชื่อ: {persona.name} (ชื่อเล่น: {persona.nickname})
อายุ: {persona.age} ปี
เพศ: {'ชาย' if persona.gender == 'male' else 'หญิง'}
ภูมิภาค: {persona.province}
อาชีพ: {persona.occupation}
รายได้: {persona.income.value}
การศึกษา: {persona.education.value}
ค่านิยมเด่น: {', '.join(v.value for v in persona.values[:3])}
สไตล์การซื้อ: {persona.decision_style.value}
บริบทภูมิภาค: {region_info['lifestyle_note']}

เขียนเป็นภาษาไทย 3-5 ประโยค เล่าเรื่องราวที่มาที่ไป ความฝัน ความกังวล พฤติกรรมการใช้จ่าย และสิ่งที่คนนี้ให้คุณค่าในชีวิต
ตอบกลับเฉพาะเนื้อเรื่อง ไม่ต้องมีคำนำหรือคำลงท้าย"""

    def _call_llm_for_narratives(
        self, prompts: List[str], language: str
    ) -> List[str]:
        """Call LLM to generate narratives. Returns one narrative per prompt."""
        narratives = []
        for prompt in prompts:
            messages = [{"role": "user", "content": prompt}]
            response = self.llm.chat(messages=messages, temperature=0.9, max_tokens=500)
            narratives.append(response.strip())
        return narratives

    def _matches_archetype(self, persona: ThaiPersona, arch: Dict[str, Any]) -> bool:
        """Check if persona roughly matches an archetype."""
        a_min, a_max = arch["age_range"]
        return (a_min <= persona.age <= a_max and
                persona.income.value == arch.get("income", ""))

    # ------------------------------------------------------------------
    # Social graph
    # ------------------------------------------------------------------

    def _assign_social_graph(self, personas: List[ThaiPersona]):
        """Assign influence relationships between personas based on similarity."""
        for i, p1 in enumerate(personas):
            for j, p2 in enumerate(personas):
                if i == j:
                    continue

                # Similarity score based on shared attributes
                score = 0.0
                if p1.region == p2.region:
                    score += 0.3
                if any(v in p2.values for v in p1.values[:2]):
                    score += 0.2
                if p1.income == p2.income:
                    score += 0.1
                if abs(p1.age - p2.age) < 10:
                    score += 0.15

                # Higher influence → others influenced by this persona
                if score > 0.5 and p1.influence_weight > p2.influence_weight:
                    p1.influences.append(p2.persona_id)
                    p2.influenced_by.append(p1.persona_id)
